# FROM ubuntu:18.04

# FROM raspbian/stretch

# FROM resin/rpi-raspbian

FROM resin/rpi-raspbian:jessie

LABEL maintainer="o.akinde@tenderd.com"

# RUN mkdir -p /usr/src/app 
# WORKDIR /app

# Minimum Linux package requirements of packages
# Install dependencies

RUN apt update && apt -y upgrade

RUN apt-get -y install build-essential checkinstall cmake pkg-config yasm \
                                                            git gfortran \
                                                            libjpeg8-dev libjasper-dev libpng12-dev \
                                                            install libtiff5-dev libtiff-dev \
                                                            libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev \
                                                            libxine2-dev libv4l-dev \
                                                            libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev \
                                                            libgtk2.0-dev libtbb-dev qt5-default \
                                                            libatlas-base-dev  wget \
                                                            libmp3lame-dev libtheora-dev \
                                                            libvorbis-dev libxvidcore-dev libx264-dev \
                                                            libopencore-amrnb-dev libopencore-amrwb-dev \
                                                            libavresample-dev x264 v4l-utils \
                                                            libprotobuf-dev protobuf-compiler \
                                                            libgoogle-glog-dev libgflags-dev \
                                                            libgphoto2-dev libeigen3-dev libhdf5-dev doxygen \
                                                            python3-dev python3-pip \
                        && pip3 install --upgrade pip \
                        && pip install --upgrade setuptools \
                        && pip3 install -U pip  numpy==1.16.2 scikit-learn==0.19.1 virtualenv tensorflow==1.14 python3-testresources


# RUN apt-get -y install build-essential checkinstall cmake pkg-config yasm
# RUN apt-get -y install git gfortran
# RUN apt-get -y install libjpeg8-dev libjasper-dev libpng12-dev
# RUN apt-get -y install libtiff5-dev libtiff-dev
# RUN apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev
# RUN apt-get install -y libxine2-dev libv4l-dev

# RUN apt-get -y install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
# RUN apt-get -y install libgtk2.0-dev libtbb-dev qt5-default
# RUN apt-get -y install libatlas-base-dev
# RUN apt-get -y install libmp3lame-dev libtheora-dev
# RUN apt-get -y install libvorbis-dev libxvidcore-dev libx264-dev
# RUN apt-get -y install libopencore-amrnb-dev libopencore-amrwb-dev
# RUN apt-get -y install libavresample-dev
# RUN apt-get -y install x264 v4l-utils

# RUN apt-get -y install libprotobuf-dev protobuf-compiler
# RUN apt-get -y install libgoogle-glog-dev libgflags-dev
# RUN apt-get -y install libgphoto2-dev libeigen3-dev libhdf5-dev doxygen

# RUN apt-get -y install python3-dev python3-pip
# RUN pip3 install -U pip  numpy==1.16.2 scikit-learn==0.19.1 virtualenv tensorflow==1.14
# RUN apt-get -y install python3-testresources

# RUN apt-get install build-essential g++ pkg-config
# RUN apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libblas-dev liblapack-dev blt-dev
# RUN apt-get install python3 python3-dev python3-matplotlib gcc gfortran musl-dev
# RUN apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

# RUN pip3 install — no-cache-dir numpy==1.16.2 scikit-learn==0.19.1



